#!/bin/bash

echo -e "Subject: $2\n`pwd` Start" | ssmtp mutien.chang@gmail.com
./run_bench.py $1 $2
./util/mstats.py -y --yaml-out $2.stats > $2.txt

./my_util/perf.py $2.log $2.txt
./my_util/cache_power.py $3
./my_util/dramsim.py
./my_util/dram_power.py

dir=$2_$3
if [ -e $dir ]
then
    echo "Warning:" $2_$3 "already exists! Store results in temp."
    mkdir temp
    mv $2.* temp
    mv *.log temp
    mv *.dat temp
else
    mkdir $2_$3
    mv $2.* $2_$3
    mv *.log $2_$3
    mv *.dat $2_$3
fi

echo -e "Subject: $2\n`pwd` Finish" | ssmtp mutien.chang@gmail.com