#!/bin/bash

# argument list:
# img benchmark memory tech_node cache_size implementation core_freq temperature num_core num_bank machine
dir=$2_$3_$4_$5_$6_$7_$8_$9_${10}_${11}

./run_bench.py $1 $2 $7 ${11}
./util/mstats.py -y --yaml-out $2.stats > $2.txt

./my_util/perf.py $2.log $2.txt $9 ${11}
./my_util/cache_power.py $3 $4 $5 $6 $7 $8 $9 ${10} ${11}
./my_util/dramsim.py
./my_util/dram_power.py

if [ -e $dir ]
then
    echo "Warning:" $dir "already exists! Store results in temp."
    mkdir temp
    mv $2.* temp
    mv *.log temp
    mv *.dat temp
else
    mkdir $dir
    mv $2.* $dir
    mv *.log $dir
    mv *.dat $dir
fi

echo -e "Subject: $dir\n $HOSTNAME:`pwd`" | ssmtp mutien.chang@gmail.com